pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "mindcraft"

include("core", "mod-fabric", "mod-forge")
